version: "3"

services:
  nginx:
    image: nginx:1-alpine
    depends_on:
      - reader-api
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf.template"
    environment:
      - "NGINX_HOST=${NGINX_HOST}"
      - "NGINX_PORT=${NGINX_PORT}"
      - "READER_API_URL=reader-api"
    command: ["/bin/sh", "-c", "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
    networks:
      - frontend
      - backend
    restart: on-failure

  reader-api:
    image: gorillab/reader-api
    environment:
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_NAME=${DB_NAME}"
      - "SESSION_SECRET=${SESSION_SECRET}"
      - "FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}"
      - "FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}"
      - "FACEBOOK_CALLBACK=${FACEBOOK_CALLBACK}"
      - "REDIRECT_URL=${REDIRECT_URL}"
    networks:
      - backend
      - db
    restart: on-failure

  reader-scraper:
    image: gorillab/reader-scraper
    environment:
      - "MONGO_URL=mongodb://${DB_HOST}:${DB_PORT}/${DB_NAME}"
      - "MAIN_CRON=${MAIN_CRON}"
    networks:
      - backend
      - db
    restart: on-failure

  mongo:
    image: mongo:3.4-jessie
    volumes:
      - "${MONGO_DIR}:/data/db"
    networks:
      - db
    restart: on-failure

networks:
  frontend:
  backend:
  db:
